"""Auth primitive regression tests.

HIGH-03 — confirms the python-jose -> PyJWT migration preserves the token
contract (payload shape, type-checking, expiry, signature checking) that
app/dependencies.py and app/routers/auth.py rely on.

LOW-01 — confirms dropping passlib for direct bcrypt calls preserves hashing
behaviour, including the >72-byte truncation passlib used to do silently and
the ``$2b$`` hash format, so credentials created before the migration still
verify afterwards.
"""

from __future__ import annotations

import pytest

from app.core.security import (
    TokenError,
    create_access_token,
    create_refresh_token,
    decode_token,
    hash_password,
    verify_password,
)
from conftest import make_settings


def test_password_hash_and_verify_roundtrip():
    hashed = hash_password("correct horse battery staple")
    assert hashed != "correct horse battery staple"
    assert verify_password("correct horse battery staple", hashed)
    assert not verify_password("wrong password", hashed)


def test_hash_is_standard_bcrypt_format():
    """Hashes written by passlib were $2b$; anything else breaks existing logins."""
    assert hash_password("whatever").startswith("$2b$")


def test_hash_of_existing_passlib_bcrypt_hash_still_verifies():
    """A bcrypt hash produced elsewhere (i.e. by the removed passlib path)
    must still verify — the stored hashes were not migrated."""
    # $2b$12$ hash of "correct horse battery staple", generated by bcrypt.
    import bcrypt
    legacy = bcrypt.hashpw(b"correct horse battery staple", bcrypt.gensalt(rounds=4)).decode()
    assert verify_password("correct horse battery staple", legacy)


def test_password_longer_than_72_bytes_does_not_raise():
    """passlib truncated silently; raw bcrypt raises on >72 bytes. The wrapper
    must keep the old behaviour or long existing passwords stop working."""
    long_password = "x" * 200
    hashed = hash_password(long_password)
    assert verify_password(long_password, hashed)


def test_multibyte_password_truncated_on_byte_boundary():
    """Truncation is by bytes, not characters — must not raise on unicode."""
    password = "🔐" * 40  # 160 bytes
    hashed = hash_password(password)
    assert verify_password(password, hashed)


def test_verify_against_malformed_hash_returns_false():
    """A corrupt stored hash is a failed login, not a 500."""
    assert not verify_password("anything", "not-a-bcrypt-hash")
    assert not verify_password("anything", "")


def test_access_token_roundtrip():
    settings = make_settings()
    token = create_access_token(settings, user_id=42)
    payload = decode_token(settings, token, expected_type="access")
    assert payload["sub"] == "42"
    assert payload["type"] == "access"


def test_refresh_token_rejected_when_expecting_access():
    settings = make_settings()
    token = create_refresh_token(settings, user_id=1)
    with pytest.raises(TokenError):
        decode_token(settings, token, expected_type="access")


def test_tampered_signature_rejected():
    settings = make_settings()
    token = create_access_token(settings, user_id=1)
    tampered = token[:-1] + ("A" if token[-1] != "A" else "B")
    with pytest.raises(TokenError):
        decode_token(settings, tampered, expected_type="access")


def test_expired_token_rejected():
    settings = make_settings(JWT_ACCESS_TTL_SECONDS=-1)
    token = create_access_token(settings, user_id=1)
    with pytest.raises(TokenError):
        decode_token(settings, token, expected_type="access")


def test_token_signed_with_different_secret_rejected():
    settings = make_settings()
    other_settings = make_settings(JWT_SECRET="a-completely-different-test-secret-000")
    token = create_access_token(settings, user_id=1)
    with pytest.raises(TokenError):
        decode_token(other_settings, token, expected_type="access")
